#!/bin/bash
#--------------
# Test a plugin
#--------------
set -e

pkg=$1
conf=$2
plugin=$3

apt-get -y install $pkg

# update plugin path and config
sed -i "s|NEUTRON_PLUGIN_CONFIG.*|NEUTRON_PLUGIN_CONFIG=\"$conf\"|g" /etc/default/neutron-server
sed -i "s/core_plugin = .*/core_plugin = $plugin/g" /etc/neutron/neutron.conf

service neutron-server restart > /dev/null 2>&1

DAEMONS=('neutron-server')
for daemon in "${DAEMONS[@]}"; do
    TIMEOUT=50
    while [ "$TIMEOUT" -gt 0 ]; do
        if service $daemon status > /dev/null; then
            echo "OK"
            break
        fi
        TIMEOUT=$((TIMEOUT - 1))
        sleep 0.5
    done

    if [ "$TIMEOUT" -le 0 ]; then
        echo "ERROR: ${daemon} IS NOT RUNNING"
        tail -50 /var/log/neutron/neutron-server.log
        apt-get -y remove --purge $pkg
        exit 1
    fi
done

apt-get -y remove --purge $pkg
